name: Run AutomationDemo

on:
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./AutomationDemo.sln

      - name: Build
        run: dotnet build ./AutomationDemo.sln --configuration Release --no-restore

      - name: Run automation
        run: dotnet test ./AutomationDemo.sln --no-build --verbosity normal
