name: Run AutomationDemo

on:
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./AutomationDemo.sln

      - name: Build
        run: dotnet build ./AutomationDemo.sln --configuration Release --no-restore

      - name: Run tests and save results
        run: dotnet test ./AutomationDemo.sln --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: '**/TestResults/*.trx'

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: AutomationDemo/Reports/Screenshots/*.png
        if: always()  # ensures screenshots are uploaded even if tests fail
